### ISSUE TITLE
Linear Regression

### ISSUE THREAD

**Issue by JanhaviSoni** [Algo-Phantoms/Algo-ScriptML#12] opened 2021-03-08 07:36 UTC
I am a participant of GSSOC'21 . I would like to contribute on Linear Regression - simple , multiple and polynomial . Please assign this issue to me.

**Comment by psyduck1203** [comment] 2021-03-08 09:45
I have already worked on this issue. The pull request is also made.

**Comment by psyduck1203** [comment] 2021-03-08 09:47
#9

**Comment by JanhaviSoni** [comment] 2021-03-09 03:14
@geekquad if this issue hasn't been assigned to anyone and if I could work on it please assign it to me. Otherwise if the pull request for this is ready to get merged so I could work on Support Vector Regression also . Please look at this.

**Comment by Sibasish-Padhy** [comment] 2021-03-12 07:27
I am a participant of GSSOC 2021 and I would like to contribute on Linear regression-one-dimensional and multi-dimensional.Please assign this issue to me

**Comment by ashwani-rathee** [comment] 2021-03-12 07:48
@Sibasish-Padhy It has been assigned for next 4 days,there are other issues that are open :)

**Closed** 2021-03-12 07:48 UTC
Labels: gssoc21

**Comment by psyduck1203** [comment] 2021-03-12 17:53
@ashwani-rathee I have already worked on this issue and made a PR 7 days ago. Only because of the checks issue #18 was failing the checks and now the issue is solved the checks are passed and the pull request is Good to go. #9
