### ISSUE TITLE
Adding code to K-Nearest Neighbours Folder

### ISSUE THREAD

**Issue by Ishan-Tewari** [Algo-Phantoms/Algo-ScriptML#147] opened 2021-03-30 11:56 UTC
Hey, I am a GSSOC 21 participant and I would like to add code for K-Nearest Neighbours implementation.

**Comment by ashwani-rathee** [comment] 2021-03-30 16:22
Duplicate of  #26 .Please claim the task there

**Closed by ashwani-rathee** 2021-03-30 16:22 UTC
Labels: Discussion, Level 3, gssoc21
