### ISSUE TITLE
Complete Program and Documentation for Naive Bayes

### ISSUE THREAD

**Issue by ashwinraj-in** [Algo-Phantoms/Algo-ScriptML#151] opened 2021-04-06 10:33 UTC
I wish to implement the Naive Bayes algorithm for Classification include the mathematics and all the details behind it. I have previously written a detailed blog explaining the entire algorithm and how Naive Bayes works under the hood.

Link to the article: https://towardsdatascience.com/the-not-so-naive-bayes-b795eaa0f69b
Can you please assign me this? Open to further discussions regarding this.

**Comment by ashwani-rathee** [comment] 2021-04-14 15:36
@ashwinraj-in This is a duplicate of #27 please get the issue assigned there

**Closed** 2021-04-14 15:36 UTC
Labels: duplicate
